# Generated by Django 3.1.1 on 2020-09-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200918_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adderss',
            new_name='address',
        ),
    ]
