# Generated by Django 3.1.1 on 2020-10-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201007_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recentSearch',
            field=models.CharField(default='{}', max_length=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendedProduct',
            field=models.CharField(default='{}', max_length=5000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart_json',
            field=models.CharField(default='{}', max_length=5000),
        ),
    ]
