# Generated by Django 3.1.1 on 2020-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_donations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='address',
            new_name='adderess',
        ),
        migrations.AddField(
            model_name='donations',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
